# Generated by Django 4.2.1 on 2023-06-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('date_of_death', models.DateField(blank=True, verbose_name='Дата смерти')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Наименование жанра')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True, verbose_name='Название')),
                ('price', models.IntegerField(blank=True, default=None, null=True, verbose_name='Цена')),
                ('release_year', models.IntegerField(blank=True, default=None, null=True, verbose_name='Год выпуска')),
                ('authors', models.ManyToManyField(to='book.author')),
                ('genres', models.ManyToManyField(to='book.genre')),
            ],
        ),
    ]
