# Generated by Django 4.2.1 on 2023-05-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
